/***************************************************************
* file: CreditsPanel.java
* author: Nicholas Pham
* class: CS 245 – Programming Graphical User Interfaces
*
* assignment: Point and Click Game – v.1.1
* date last modified: 10/07/2017
*
* purpose: This class builds the panel which displays the game credits
*
****************************************************************/

package cs245p1;

import javax.swing.JButton;

/**
 * this class is the panel that displays who created the game/project
 */
public class CreditsPanel extends javax.swing.JPanel {
    
    //Please note: Auto-generated instance variables are automatically placed at the end of the class definition and cannot be moved
    
    // method: CreditsPanel
    // purpose: constructor
    public CreditsPanel() {
        initComponents();
    }
    
    // method: getBackButton
    // purpose: return to main menu
    public JButton getBackButton() {
        return backButton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creditsLabel = new javax.swing.JLabel();
        chrisNameLabel = new javax.swing.JLabel();
        andrewNameLabel = new javax.swing.JLabel();
        nickNameLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setPreferredSize(new java.awt.Dimension(600, 400));

        creditsLabel.setBackground(java.awt.Color.black);
        creditsLabel.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        creditsLabel.setForeground(java.awt.Color.white);
        creditsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditsLabel.setText("CREDITS");
        creditsLabel.setToolTipText("creditsTitle");
        creditsLabel.setAlignmentY(0.0F);
        creditsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        creditsLabel.setVerifyInputWhenFocusTarget(false);

        chrisNameLabel.setBackground(java.awt.Color.black);
        chrisNameLabel.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        chrisNameLabel.setForeground(java.awt.Color.white);
        chrisNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chrisNameLabel.setText("Christopher Kilian, Bronco #012122383");
        chrisNameLabel.setToolTipText("creditsChristopher");

        andrewNameLabel.setBackground(java.awt.Color.black);
        andrewNameLabel.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        andrewNameLabel.setForeground(java.awt.Color.white);
        andrewNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        andrewNameLabel.setText("Andrew Tek, Bronco #009604621");
        andrewNameLabel.setToolTipText("creditsAndrew");

        nickNameLabel.setBackground(java.awt.Color.black);
        nickNameLabel.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        nickNameLabel.setForeground(java.awt.Color.white);
        nickNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nickNameLabel.setText("Nicholas Pham, Bronco #010186410");
        nickNameLabel.setToolTipText("creditsNicholas");

        backButton.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        backButton.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(creditsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(0, 501, Short.MAX_VALUE))
                    .addComponent(chrisNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(andrewNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nickNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(creditsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chrisNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(andrewNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nickNameLabel)
                .addGap(98, 98, 98)
                .addComponent(backButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel andrewNameLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel chrisNameLabel;
    private javax.swing.JLabel creditsLabel;
    private javax.swing.JLabel nickNameLabel;
    // End of variables declaration//GEN-END:variables
}
