/***************************************************************
* file: GameOverPanel.java
* author: Christopher Kilian, Nicholas Pham
* class: CS 245 – Programming Graphical User Interfaces
*
* assignment: Point and Click Game – v.1.1
* date last modified: 10/18/2017
*
* purpose: This class defines the panel which displays the game over screen
* and the players score for the game
*
****************************************************************/
package cs245p1;

import javax.swing.JButton;
import javax.swing.JOptionPane;

public class GameOverPanel extends javax.swing.JPanel {

    //Please note: Auto-generated instance variables are automatically placed at the end of the class definition and cannot be moved
    
    private HighScoresList highScores = new HighScoresList();
    
    // method: GameOverPanel
    // purpose: constructor
    public GameOverPanel() {
        initComponents();
    }
    
    // method: checkForHighScore
    // purpose: method which will check the score of the most recently played hangman and color games.
    //If the score is a high score, it asks the player if they want to enter their initials (1 to 3 characters)
    //and if they do, it will save their score. If they click cancel, nothing is done.
    public void checkForHighScore(){
        int score = CS245P1.getGame().getPoints() + CS245P1.getColorGame().getPoints();
        highScores.sortScores();
        if (highScores.checkIfHighScore(score)) {
            GameOverPanel gameOver = (GameOverPanel)CS245P1.getPanelMap().get(CS245P1.GAME_OVER);
            
            String response = (String)JOptionPane.showInputDialog(
                        gameOver,
                        "Congratulations on your high score! \n"
                        + "Please enter your initials (no more than 3)",
                        "High Score!",
                        JOptionPane.PLAIN_MESSAGE);
            while(response != null && ((response.length() == 0) || (response.length() > 3))){
                response = (String)JOptionPane.showInputDialog(
                        gameOver,
                        "To record your score, please enter between 1 and 3 initials only!",
                        "High Score!",
                        JOptionPane.PLAIN_MESSAGE);
            }
            
            //if user clicks "cancel" on dialog box, response will be null and no action should be taken (user declined saving high score)
            if(response != null){
                Scores newScore = new Scores(response, score);
                highScores.addScore(newScore);
                highScores.sortScores();
                highScores.update();
                
                HighScoresPanel scoresPanel = (HighScoresPanel)CS245P1.getPanelMap().get(CS245P1.HIGH_SCORES);
                scoresPanel.updateHighScoresList(highScores);
                scoresPanel.updateScoresView();
            }
        }
    }
    
    
    // method: setScore
    // purpose: sets the score label with the most recent game score
    public void setScore(){
        int totalPoints = CS245P1.getGame().getPoints() + CS245P1.getColorGame().getPoints();
        scoreLabel.setText("Your Score: " + totalPoints);
        
    }

    // method: getEndButton
    // purpose: getter for the "end" button
    public JButton getEndButton() {
        return endButton;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameOverLabel = new javax.swing.JLabel();
        endButton = new javax.swing.JButton();
        scoreLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 400));

        gameOverLabel.setFont(new java.awt.Font("Century", 3, 36)); // NOI18N
        gameOverLabel.setForeground(new java.awt.Color(255, 51, 0));
        gameOverLabel.setText("Game Over");

        endButton.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        endButton.setText("End");

        scoreLabel.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        scoreLabel.setText("Your Score: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(endButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gameOverLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(gameOverLabel)
                .addGap(53, 53, 53)
                .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(endButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton endButton;
    private javax.swing.JLabel gameOverLabel;
    private javax.swing.JLabel scoreLabel;
    // End of variables declaration//GEN-END:variables
}
