/***************************************************************
* file: HighScoresPanel.java
* author: Nicholas Pham, Christopher Kilian
* class: CS 245 – Programming Graphical User Interfaces
*
* assignment: Point and Click Game – v.1.1
* date last modified: 10/18/2017
*
* purpose: This class builds the panel which displays the high scores
*
****************************************************************/

package cs245p1;

import javax.swing.JButton;

/**
 * this class is the panel that displays the top five high scores
 */
public class HighScoresPanel extends javax.swing.JPanel {
    
    //Please note: Auto-generated instance variables are automatically placed at the end of the class definition and cannot be moved
    
    // high scores list
    private HighScoresList highScoresList;

    // method: highScoresPanel
    // purpose: build panel to display high scores
    public HighScoresPanel() {
        highScoresList = new HighScoresList();
        highScoresList.sortScores();
        initComponents();
        updateScoresView();
    }
    
    // method: updateHighScoresList
    // purpose: reset the high scores list to point to a new one (needed to update list on panel)
    public void updateHighScoresList(HighScoresList newHighScoreList){
        highScoresList = newHighScoreList;
    }
    
    // method: updateScoresView
    // purpose: updates the listed scores visible on the panel
    public void updateScoresView(){
        /* DISPLAY HIGH SCORES */
        // Reads first in high scores list, which is sorted to be the highest and prints the player name and their score
        highScore1.setText(highScoresList.getScores().get(0).getPlayer() + " - " + String.format("%06d", highScoresList.getScores().get(0).getScore()));
        // Reads second in high scores list, which is sorted to be the highest and prints the player name and their score
        highScore2.setText(highScoresList.getScores().get(1).getPlayer() + " - " + String.format("%06d", highScoresList.getScores().get(1).getScore()));
        // Reads third in high scores list, which is sorted to be the highest and prints the player name and their score
        highScore3.setText(highScoresList.getScores().get(2).getPlayer() + " - " + String.format("%06d", highScoresList.getScores().get(2).getScore()));
        // Reads fourth in high scores list, which is sorted to be the highest and prints the player name and their score
        highScore4.setText(highScoresList.getScores().get(3).getPlayer() + " - " + String.format("%06d", highScoresList.getScores().get(3).getScore()));
        // Reads fifth in high scores list, which is sorted to be the highest and prints the player name and their score
        highScore5.setText(highScoresList.getScores().get(4).getPlayer() + " - " + String.format("%06d", highScoresList.getScores().get(4).getScore()));
        repaint();
    }
    
    // method: getBackButton
    // purpose: return to main menu
    public JButton getBackButton() {
        return highScoresBackButton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scoresTitle = new javax.swing.JLabel();
        highScore1 = new javax.swing.JLabel();
        highScore2 = new javax.swing.JLabel();
        highScore3 = new javax.swing.JLabel();
        highScore4 = new javax.swing.JLabel();
        highScore5 = new javax.swing.JLabel();
        highScoresBackButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setPreferredSize(new java.awt.Dimension(600, 400));

        scoresTitle.setBackground(java.awt.Color.black);
        scoresTitle.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        scoresTitle.setForeground(java.awt.Color.white);
        scoresTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoresTitle.setText("HIGH SCORES");
        scoresTitle.setToolTipText("scoresTitle");
        scoresTitle.setAlignmentY(0.0F);
        scoresTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        highScore1.setBackground(java.awt.Color.black);
        highScore1.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        highScore1.setForeground(java.awt.Color.white);
        highScore1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highScore1.setToolTipText("highScore1");

        highScore2.setBackground(java.awt.Color.black);
        highScore2.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        highScore2.setForeground(java.awt.Color.white);
        highScore2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highScore2.setToolTipText("highScore2");

        highScore3.setBackground(java.awt.Color.black);
        highScore3.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        highScore3.setForeground(java.awt.Color.white);
        highScore3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highScore3.setToolTipText("highScore3");

        highScore4.setBackground(java.awt.Color.black);
        highScore4.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        highScore4.setForeground(java.awt.Color.white);
        highScore4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highScore4.setToolTipText("highScore4");

        highScore5.setBackground(java.awt.Color.black);
        highScore5.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        highScore5.setForeground(java.awt.Color.white);
        highScore5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highScore5.setToolTipText("highScore5");

        highScoresBackButton.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        highScoresBackButton.setText("Back");
        highScoresBackButton.setActionCommand("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scoresTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(highScoresBackButton)
                        .addGap(0, 477, Short.MAX_VALUE))
                    .addComponent(highScore1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                    .addComponent(highScore2, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                    .addComponent(highScore3, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                    .addComponent(highScore4, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                    .addComponent(highScore5, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(scoresTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(highScore1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(highScore2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(highScore3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(highScore4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(highScore5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(highScoresBackButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel highScore1;
    private javax.swing.JLabel highScore2;
    private javax.swing.JLabel highScore3;
    private javax.swing.JLabel highScore4;
    private javax.swing.JLabel highScore5;
    private javax.swing.JButton highScoresBackButton;
    private javax.swing.JLabel scoresTitle;
    // End of variables declaration//GEN-END:variables
}
